
import java.util.Scanner;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author akash
 */
import java.util.Scanner;
import static java.lang.System.out;

public class FrmDecisionsForm extends javax.swing.JFrame {

    /**
     * Creates new form Frame7
     */
    public FrmDecisionsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNameDrink1 = new javax.swing.JLabel();
        txtSizeDrink1 = new javax.swing.JTextField();
        txtQuantityDrink1 = new javax.swing.JTextField();
        lblTotalPriceDrink1 = new javax.swing.JLabel();
        lblAssignmentTitle = new javax.swing.JLabel();
        lblPromotion1Details = new javax.swing.JLabel();
        lblSizePriceDrink1 = new javax.swing.JLabel();
        lblSizeOptions = new javax.swing.JLabel();
        lblQuantityOptions = new javax.swing.JLabel();
        lblPriceValues = new javax.swing.JLabel();
        lblNameDrink2 = new javax.swing.JLabel();
        txtSizeDrink2 = new javax.swing.JTextField();
        txtQuantityDrink2 = new javax.swing.JTextField();
        lblTotalPriceDrink2 = new javax.swing.JLabel();
        lblSizePriceDrink2 = new javax.swing.JLabel();
        lblNameDrink3 = new javax.swing.JLabel();
        txtSizeDrink3 = new javax.swing.JTextField();
        txtQuantityDrink3 = new javax.swing.JTextField();
        lblTotalPriceDrink3 = new javax.swing.JLabel();
        lblSizePriceDrink3 = new javax.swing.JLabel();
        lblNameDrink4 = new javax.swing.JLabel();
        txtSizeDrink4 = new javax.swing.JTextField();
        txtQuantityDrink4 = new javax.swing.JTextField();
        lblTotalPriceDrink4 = new javax.swing.JLabel();
        lblSizePriceDrink4 = new javax.swing.JLabel();
        lblNameDrink5 = new javax.swing.JLabel();
        txtSizeDrink5 = new javax.swing.JTextField();
        txtQuantityDrink5 = new javax.swing.JTextField();
        lblTotalPriceDrink5 = new javax.swing.JLabel();
        lblSizePriceDrink5 = new javax.swing.JLabel();
        lblNameDrink6 = new javax.swing.JLabel();
        txtSizeDrink6 = new javax.swing.JTextField();
        txtQuantityDrink6 = new javax.swing.JTextField();
        lblTotalPriceDrink6 = new javax.swing.JLabel();
        lblSizePriceDrink6 = new javax.swing.JLabel();
        lblDummyLine1 = new javax.swing.JLabel();
        lblPromotion1Description = new javax.swing.JLabel();
        lblPromotion1Savings = new javax.swing.JLabel();
        lblPurchasePriceDescription = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblPurchasePrice = new javax.swing.JLabel();
        lblPromotion2Description = new javax.swing.JLabel();
        lblPromotion2Savings = new javax.swing.JLabel();
        lblSubtotalDescription = new javax.swing.JLabel();
        lblSubtotalPrice = new javax.swing.JLabel();
        lblTaxDescription = new javax.swing.JLabel();
        lblTaxPrice = new javax.swing.JLabel();
        lblDummyLine2 = new javax.swing.JLabel();
        lblFinalPriceDescription = new javax.swing.JLabel();
        lblFinalPrice = new javax.swing.JLabel();
        lblFinalSavings = new javax.swing.JLabel();
        lblPromotion2Details = new javax.swing.JLabel();
        lblDummyLine3 = new javax.swing.JLabel();
        lblDummyLine4 = new javax.swing.JLabel();
        lblSLrep = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblIntroduction = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNameDrink1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNameDrink1.setText("TTime Pearl Milk Tea                                 :");

        txtSizeDrink1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSizeDrink1.setText("0");
        txtSizeDrink1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSizeDrink1ActionPerformed(evt);
            }
        });

        txtQuantityDrink1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantityDrink1.setText("0");
        txtQuantityDrink1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityDrink1ActionPerformed(evt);
            }
        });

        lblTotalPriceDrink1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalPriceDrink1.setText(" ");

        lblAssignmentTitle.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        lblAssignmentTitle.setForeground(new java.awt.Color(255, 0, 51));
        lblAssignmentTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAssignmentTitle.setText("Tea Time");

        lblPromotion1Details.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblPromotion1Details.setForeground(new java.awt.Color(0, 0, 255));
        lblPromotion1Details.setText("Promotion 1 :  This week only.  Buy 4 or more drinks (any Size) and get 1 drink for free");

        lblSizePriceDrink1.setText("S - $4.99    :    L - $5.99");

        lblSizeOptions.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSizeOptions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSizeOptions.setText("Size");

        lblQuantityOptions.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuantityOptions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantityOptions.setText("Quantity");

        lblPriceValues.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPriceValues.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPriceValues.setText("Price");

        lblNameDrink2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNameDrink2.setText("TT Mango Juice                                         :");

        txtSizeDrink2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSizeDrink2.setText("0");

        txtQuantityDrink2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantityDrink2.setText("0");

        lblTotalPriceDrink2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalPriceDrink2.setText(" ");

        lblSizePriceDrink2.setText("S - $5.25    :    L - $5.75");

        lblNameDrink3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNameDrink3.setText("TT Signature Mint Tea                              :");

        txtSizeDrink3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSizeDrink3.setText("0");

        txtQuantityDrink3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantityDrink3.setText("0");

        lblTotalPriceDrink3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalPriceDrink3.setText(" ");

        lblSizePriceDrink3.setText("S - $3.99    :    L - $4.50");

        lblNameDrink4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNameDrink4.setText("Organic Coconut Juice                             :");

        txtSizeDrink4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSizeDrink4.setText("0");

        txtQuantityDrink4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantityDrink4.setText("0");

        lblTotalPriceDrink4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalPriceDrink4.setText(" ");

        lblSizePriceDrink4.setText("S - $4.99    :    L - $5.50");

        lblNameDrink5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNameDrink5.setText("Strawberry Milk Shake                             :");

        txtSizeDrink5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSizeDrink5.setText("0");

        txtQuantityDrink5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantityDrink5.setText("0");

        lblTotalPriceDrink5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalPriceDrink5.setText(" ");

        lblSizePriceDrink5.setText("S - $3.75    :    L - $4.25");

        lblNameDrink6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNameDrink6.setText("Hot Chocolate                                           :");

        txtSizeDrink6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSizeDrink6.setText("0");

        txtQuantityDrink6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantityDrink6.setText("0");

        lblTotalPriceDrink6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalPriceDrink6.setText(" ");

        lblSizePriceDrink6.setText("S - $7.25    :    L - $8.00");

        lblDummyLine1.setText("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        lblPromotion1Description.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblPromotion1Description.setText("Promotion 1 - Free Drink applied                      ");

        lblPromotion1Savings.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPromotion1Savings.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPromotion1Savings.setText(" ");

        lblPurchasePriceDescription.setText("Purchase Price (after Promotion 1)                               ");

        btnCheckout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCheckout.setText("CHECKOUT");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblPurchasePrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPurchasePrice.setText(" ");

        lblPromotion2Description.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblPromotion2Description.setText("Promotion 2 - 20% Discount                           ");

        lblPromotion2Savings.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPromotion2Savings.setText(" ");

        lblSubtotalDescription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSubtotalDescription.setText("SUBTOTAL  (After all Promotions applied)   ");

        lblSubtotalPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSubtotalPrice.setText(" ");

        lblTaxDescription.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTaxDescription.setText("Tax (13%)    ");

        lblTaxPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTaxPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTaxPrice.setText(" ");

        lblDummyLine2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDummyLine2.setText("-------------------");

        lblFinalPriceDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFinalPriceDescription.setText("FINAL Price                                        ");

        lblFinalPrice.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblFinalPrice.setText(" ");

        lblFinalSavings.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblFinalSavings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinalSavings.setText(" ");

        lblPromotion2Details.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblPromotion2Details.setForeground(new java.awt.Color(0, 0, 255));
        lblPromotion2Details.setText("Promotion 2 :  Get 20% discount on your order of $20 or more (excluding Promotion 1 and Tax)");

        lblDummyLine3.setText("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        lblDummyLine4.setText("---------------------");

        lblSLrep.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSLrep.setText("S = 0 / L = 1");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TeaTimeLogo.png"))); // NOI18N
        lblLogo.setText("jLabel3");

        lblIntroduction.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIntroduction.setText("Hello, welcome to Tea Time.   Our store is a great place to chat & cherish our tasty beverages.   Hope you have a great time chatting!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSLrep)
                .addGap(437, 437, 437))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPromotion2Details, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPromotion1Details, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(lblSizePriceDrink1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(lblSizePriceDrink2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(372, 372, 372)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtSizeDrink1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblSizeOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtSizeDrink2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(59, 59, 59)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(lblQuantityOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(98, 98, 98)
                                                    .addComponent(lblPriceValues, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtQuantityDrink2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txtQuantityDrink1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(173, 173, 173))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addComponent(txtQuantityDrink3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(txtQuantityDrink4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(txtQuantityDrink5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(txtQuantityDrink6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lblTotalPriceDrink2)
                                                            .addComponent(lblTotalPriceDrink1)
                                                            .addComponent(lblTotalPriceDrink3)
                                                            .addComponent(lblTotalPriceDrink5)
                                                            .addComponent(lblTotalPriceDrink4)
                                                            .addComponent(lblTotalPriceDrink6))))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(lblSizePriceDrink3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(lblSizePriceDrink4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(lblSizePriceDrink5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(lblSizePriceDrink6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblDummyLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblNameDrink2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblNameDrink1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblNameDrink3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblNameDrink4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblNameDrink5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblNameDrink6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(90, 90, 90)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtSizeDrink3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtSizeDrink4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtSizeDrink5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtSizeDrink6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(254, 254, 254)
                                            .addComponent(btnCheckout)
                                            .addGap(77, 77, 77)
                                            .addComponent(btnClear))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(303, 303, 303)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblTaxDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblSubtotalDescription)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblPurchasePriceDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblPromotion1Description)
                                                        .addComponent(lblPromotion2Description))
                                                    .addComponent(lblFinalPriceDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(72, 72, 72)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(33, 33, 33)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblPromotion1Savings)
                                                        .addComponent(lblPurchasePrice)
                                                        .addComponent(lblPromotion2Savings)
                                                        .addComponent(lblSubtotalPrice)
                                                        .addComponent(lblTaxPrice)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(28, 28, 28)
                                                    .addComponent(lblFinalPrice)))
                                            .addGap(13, 13, 13))
                                        .addComponent(lblDummyLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(639, 639, 639)
                                            .addComponent(lblDummyLine4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(639, 639, 639)
                                        .addComponent(lblDummyLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblIntroduction)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblFinalSavings, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAssignmentTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAssignmentTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGap(26, 26, 26)
                .addComponent(lblIntroduction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPromotion1Details, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPromotion2Details, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lblDummyLine3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSizeOptions)
                            .addComponent(lblQuantityOptions)
                            .addComponent(lblPriceValues))
                        .addGap(4, 4, 4)
                        .addComponent(lblSLrep)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSizeDrink1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantityDrink1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalPriceDrink1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblNameDrink1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSizePriceDrink1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameDrink2)
                    .addComponent(txtSizeDrink2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantityDrink2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPriceDrink2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSizePriceDrink2)
                        .addGap(26, 26, 26)
                        .addComponent(lblNameDrink3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSizeDrink3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtQuantityDrink3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTotalPriceDrink3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSizePriceDrink3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSizeDrink4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtQuantityDrink4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTotalPriceDrink4))
                    .addComponent(lblNameDrink5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSizePriceDrink4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameDrink4)
                    .addComponent(txtSizeDrink5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantityDrink5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPriceDrink5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSizePriceDrink5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameDrink6)
                    .addComponent(txtSizeDrink6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantityDrink6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPriceDrink6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSizePriceDrink6)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckout)
                    .addComponent(btnClear))
                .addGap(27, 27, 27)
                .addComponent(lblDummyLine1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPromotion1Description)
                    .addComponent(lblPromotion1Savings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDummyLine4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPurchasePriceDescription)
                    .addComponent(lblPurchasePrice))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPromotion2Description)
                    .addComponent(lblPromotion2Savings))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotalDescription)
                    .addComponent(lblSubtotalPrice))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxDescription)
                    .addComponent(lblTaxPrice))
                .addGap(18, 18, 18)
                .addComponent(lblDummyLine2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFinalPriceDescription)
                    .addComponent(lblFinalPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(lblFinalSavings, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      
    private void txtSizeDrink1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSizeDrink1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtSizeDrink1ActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
     
        Scanner keyedInput = new Scanner(System.in);
        
        //declaring final values for all drinks (all sizes)
        final double S_DRINK1_PRICE = 4.99;
        final double L_DRINK1_PRICE = 5.99;
        final double S_DRINK2_PRICE = 5.25;
        final double L_DRINK2_PRICE = 5.75;
        final double S_DRINK3_PRICE = 3.99;
        final double L_DRINK3_PRICE = 4.50; 
        final double S_DRINK4_PRICE = 4.99;
        final double L_DRINK4_PRICE = 5.50;
        final double S_DRINK5_PRICE = 3.75;
        final double L_DRINK5_PRICE = 4.25;
        final double S_DRINK6_PRICE = 7.25;
        final double L_DRINK6_PRICE = 8.00;
        
        //declaring final values for Promotion 2 Percentage and Tax Rate
        final double PROMOTION2_PERCENTAGE = 0.20;
        final double TAX_RATE = 0.13;
        
        //integer variables declared to store the Size of the Drink provided as input by User
        int Size_Drink1;
        int Size_Drink2;
        int Size_Drink3;
        int Size_Drink4;
        int Size_Drink5;
        int Size_Drink6;
        
        //integer variables declared to store the Quantity of the Drink provided as input by User
        int Quantity_Drink1;
        int Quantity_Drink2;
        int Quantity_Drink3;
        int Quantity_Drink4;
        int Quantity_Drink5;
        int Quantity_Drink6;
        
        //double variables declared to store Total Price for each drink based on the Size and Quantity
        double Total_Price_Drink1;
        double Total_Price_Drink2;
        double Total_Price_Drink3;
        double Total_Price_Drink4;
        double Total_Price_Drink5;
        double Total_Price_Drink6;
        
        //integer and double variables declared to store Total Drink Count and Promotional Savings/Prices, which are initialized to zeroes
        int Total_Drinks_Count = 0;
        double Total_Drinks_Price = 0;
        double Promotion1_Temp_Price = 0;
        double Promotion1_Savings = 0;
        double Purchase_Price = 0;
        double Promotion2_Savings = 0;
        
        //double variables declared to store Subtotal, Tax Price, Final Price and Final Savings, which are initialized to zeroes
        double Subtotal_Price = 0;
        double Tax_Price = 0;
        double Final_Price = 0;
        double Final_Savings = 0;

        //Get inputs from user on both Size and Quantity for all 6 drinks being offered
        Size_Drink1 = Integer.parseInt(txtSizeDrink1.getText());
        Quantity_Drink1 = Integer.parseInt(txtQuantityDrink1.getText());
        Size_Drink2 = Integer.parseInt(txtSizeDrink2.getText());
        Quantity_Drink2 = Integer.parseInt(txtQuantityDrink2.getText());
        Size_Drink3 = Integer.parseInt(txtSizeDrink3.getText());
        Quantity_Drink3 = Integer.parseInt(txtQuantityDrink3.getText());
        Size_Drink4 = Integer.parseInt(txtSizeDrink4.getText());
        Quantity_Drink4 = Integer.parseInt(txtQuantityDrink4.getText());
        Size_Drink5 = Integer.parseInt(txtSizeDrink5.getText());
        Quantity_Drink5 = Integer.parseInt(txtQuantityDrink5.getText());
        Size_Drink6 = Integer.parseInt(txtSizeDrink6.getText());
        Quantity_Drink6 = Integer.parseInt(txtQuantityDrink6.getText());
        
        //***************************   Logic for Drink 1  ***********************************
        //Calculate the Total Price of Drink1 based on the Size & Quantity inputted by User and display Total_Price for Drink1 limiting to 2 decimals
        if (Quantity_Drink1 >0)
        {
            if (Size_Drink1 == 1)
            {
                Total_Price_Drink1 = L_DRINK1_PRICE * Quantity_Drink1;
                Promotion1_Temp_Price = L_DRINK1_PRICE;
            }
            else
            {
                Total_Price_Drink1 = S_DRINK1_PRICE * Quantity_Drink1;
                Promotion1_Temp_Price = S_DRINK1_PRICE;
                txtSizeDrink1.setText("0");
            }
            lblTotalPriceDrink1.setText(String.format("$ "+"%.2f",Total_Price_Drink1));
            
            //Calculate the total_drinks_count and total_drinks_price, when user has provided quantity of Drink1 > 0
            Total_Drinks_Count = Total_Drinks_Count + Quantity_Drink1;
            Total_Drinks_Price = Total_Drinks_Price + Total_Price_Drink1;
            
           //Check lowest priced drink, incase eligbible for Promotion 1 (Free drink if Total Drink count > 3)
           if (Promotion1_Savings < Promotion1_Temp_Price)
           {
                if (Promotion1_Savings == 0)
                {
                    Promotion1_Savings =  Promotion1_Temp_Price;  
                }
           }
           else
           {
               Promotion1_Savings =  Promotion1_Temp_Price; 
           }
        }
        else
        { 
            Total_Price_Drink1 = 0;
            lblTotalPriceDrink1.setText(String.format("$ "+"%.2f",Total_Price_Drink1)); 
        }
       
        //***************************   Logic for Drink 2  ***********************************
        //Calculate the Total Price of Drink2 based on the Size & Quantity inputted by User and display Total_Price for Drink2 limiting to 2 decimals
        if (Quantity_Drink2 >0)
        {
            if (Size_Drink2 == 1)
            {
                Total_Price_Drink2 = L_DRINK2_PRICE * Quantity_Drink2;
                Promotion1_Temp_Price = L_DRINK2_PRICE;
            }
            else
            {
                Total_Price_Drink2 = S_DRINK2_PRICE * Quantity_Drink2;
                Promotion1_Temp_Price = S_DRINK2_PRICE;
                txtSizeDrink2.setText("0");
            }
            lblTotalPriceDrink2.setText(String.format("$ "+"%.2f",Total_Price_Drink2));
            
            //Calculate the total_drinks_count and total_drinks_price, when user has provided quantity of Drink2 > 0
            Total_Drinks_Count = Total_Drinks_Count + Quantity_Drink2;
            Total_Drinks_Price = Total_Drinks_Price + Total_Price_Drink2;
            
           //Check lowest priced drink, incase eligbible for Promotion 1 (Free drink if Total Drink count > 3)
           if (Promotion1_Savings < Promotion1_Temp_Price)
           {
                if (Promotion1_Savings == 0)
                {
                    Promotion1_Savings =  Promotion1_Temp_Price;  
                }
           }
           else
           {
               Promotion1_Savings =  Promotion1_Temp_Price; 
           }
        }
        else
        { 
            Total_Price_Drink2 = 0;
            lblTotalPriceDrink2.setText(String.format("$ "+"%.2f",Total_Price_Drink2)); 
        }
        
        //***************************   Logic for Drink 3  ***********************************
        //Calculate the Total Price of Drink3 based on the Size & Quantity inputted by User and display Total_Price for Drink3 limiting to 2 decimals
        if (Quantity_Drink3 >0)
        {
            if (Size_Drink3 == 1)
            {
                Total_Price_Drink3 = L_DRINK3_PRICE * Quantity_Drink3;
                Promotion1_Temp_Price = L_DRINK3_PRICE;
            }
            else
            {
                Total_Price_Drink3 = S_DRINK3_PRICE * Quantity_Drink3;
                Promotion1_Temp_Price = S_DRINK3_PRICE;
                txtSizeDrink3.setText("0");
            }
            lblTotalPriceDrink3.setText(String.format("$ "+"%.2f",Total_Price_Drink3));
            
            //Calculate the total_drinks_count and total_drinks_price, when user has provided quantity of Drink3 > 0
            Total_Drinks_Count = Total_Drinks_Count + Quantity_Drink3;
            Total_Drinks_Price = Total_Drinks_Price + Total_Price_Drink3;
            
           //Check lowest priced drink, incase eligbible for Promotion 1 (Free drink if Total Drink count > 3)
           if (Promotion1_Savings < Promotion1_Temp_Price)
           {
                if (Promotion1_Savings == 0)
                {
                    Promotion1_Savings =  Promotion1_Temp_Price;  
                }
           }
           else
           {
               Promotion1_Savings =  Promotion1_Temp_Price; 
           }
        }
        else
        { 
            Total_Price_Drink3 = 0;
            lblTotalPriceDrink3.setText(String.format("$ "+"%.2f",Total_Price_Drink3)); 
        }

        //***************************   Logic for Drink 4  ***********************************
        //Calculate the Total Price of Drink4 based on the Size & Quantity inputted by User and display Total_Price for Drink4 limiting to 2 decimals
        if (Quantity_Drink4 >0)
        {
            if (Size_Drink4 == 1)
            {
                Total_Price_Drink4 = L_DRINK4_PRICE * Quantity_Drink4;
                Promotion1_Temp_Price = L_DRINK4_PRICE;
            }
            else
            {
                Total_Price_Drink4 = S_DRINK4_PRICE * Quantity_Drink4;
                Promotion1_Temp_Price = S_DRINK4_PRICE;
                txtSizeDrink4.setText("0");
            }
            lblTotalPriceDrink4.setText(String.format("$ "+"%.2f",Total_Price_Drink4));
            
            //Calculate the total_drinks_count and total_drinks_price, when user has provided quantity of Drink4 > 0
            Total_Drinks_Count = Total_Drinks_Count + Quantity_Drink4;
            Total_Drinks_Price = Total_Drinks_Price + Total_Price_Drink4;
            
           //Check lowest priced drink, incase eligbible for Promotion 1 (Free drink if Total Drink count > 3)
           if (Promotion1_Savings < Promotion1_Temp_Price)
           {
                if (Promotion1_Savings == 0)
                {
                    Promotion1_Savings =  Promotion1_Temp_Price;  
                }
           }
           else
           {
               Promotion1_Savings =  Promotion1_Temp_Price; 
           }
        }
        else
        { 
            Total_Price_Drink4 = 0;
            lblTotalPriceDrink4.setText(String.format("$ "+"%.2f",Total_Price_Drink4)); 
        }
        
        //***************************   Logic for Drink 5  ***********************************
        //Calculate the Total Price of Drink5 based on the Size & Quantity inputted by User and display Total_Price for Drink5 limiting to 2 decimals
        if (Quantity_Drink5 >0)
        {
            if (Size_Drink5 == 1)
            {
                Total_Price_Drink5 = L_DRINK5_PRICE * Quantity_Drink5;
                Promotion1_Temp_Price = L_DRINK5_PRICE;
            }
            else
            {
                Total_Price_Drink5 = S_DRINK5_PRICE * Quantity_Drink5;
                Promotion1_Temp_Price = S_DRINK5_PRICE;
                txtSizeDrink5.setText("0");
            }
            lblTotalPriceDrink5.setText(String.format("$ "+"%.2f",Total_Price_Drink5));
            
            //Calculate the total_drinks_count and total_drinks_price, when user has provided quantity of Drink5 > 0
            Total_Drinks_Count = Total_Drinks_Count + Quantity_Drink5;
            Total_Drinks_Price = Total_Drinks_Price + Total_Price_Drink5;
            
           //Check lowest priced drink, incase eligbible for Promotion 1 (Free drink if Total Drink count > 3)
           if (Promotion1_Savings < Promotion1_Temp_Price)
           {
                if (Promotion1_Savings == 0)
                {
                    Promotion1_Savings =  Promotion1_Temp_Price;  
                }
           }
           else
           {
               Promotion1_Savings =  Promotion1_Temp_Price; 
           }
        }
        else
        { 
            Total_Price_Drink5 = 0;
            lblTotalPriceDrink5.setText(String.format("$ "+"%.2f",Total_Price_Drink5)); 
        }
        
        //***************************   Logic for Drink 6  ***********************************
        //Calculate the Total Price of Drink6 based on the Size & Quantity inputted by User and display Total_Price for Drink6 limiting to 2 decimals
        if (Quantity_Drink6 >0)
        {
            if (Size_Drink6 == 1)
            {
                Total_Price_Drink6 = L_DRINK6_PRICE * Quantity_Drink6;
                Promotion1_Temp_Price = L_DRINK6_PRICE;
            }
            else
            {
                Total_Price_Drink6 = S_DRINK6_PRICE * Quantity_Drink6;
                Promotion1_Temp_Price = S_DRINK6_PRICE;
                txtSizeDrink6.setText("0");
            }
            lblTotalPriceDrink6.setText(String.format("$ "+"%.2f",Total_Price_Drink6));
            
            //Calculate the total_drinks_count and total_drinks_price, when user has provided quantity of Drink6 > 0
            Total_Drinks_Count = Total_Drinks_Count + Quantity_Drink6;
            Total_Drinks_Price = Total_Drinks_Price + Total_Price_Drink6;
            
           //Check lowest priced drink, incase eligbible for Promotion 1 (Free drink if Total Drink count > 3)
           if (Promotion1_Savings < Promotion1_Temp_Price)
           {
                if (Promotion1_Savings == 0)
                {
                    Promotion1_Savings =  Promotion1_Temp_Price;  
                }
           }
           else
           {
               Promotion1_Savings =  Promotion1_Temp_Price; 
           }
        }
        else
        { 
            Total_Price_Drink6 = 0;
            lblTotalPriceDrink6.setText(String.format("$ "+"%.2f",Total_Price_Drink6)); 
        }
        
        // Applying Promotion 1 criteria
        // check for eligibility of Promotion 1 (free drink - lowest priced drink) which can be applied only if the total drinks > 3
        if (Total_Drinks_Count > 3)
        {
            lblPromotion1Savings.setText(String.format("$ "+"%.2f",Promotion1_Savings)+"  -");
        }
        else
        {
            Promotion1_Savings = 0;
            lblPromotion1Savings.setText(String.format("$ "+"%.2f",Promotion1_Savings));
        }
        
        // Calculate Purchase price, by adding up total price for each drink purchases and deducting the Promotion 1 free drink
        Purchase_Price = Total_Drinks_Price - Promotion1_Savings;
        lblPurchasePrice.setText(String.format("$ "+"%.2f",Purchase_Price));
         
        // Applying Promotion 2 criteria
        // check for eligibility of Promotion 2 (20% off) if total purchase price is > $20
        if (Purchase_Price > 20)
        {
            Promotion2_Savings = Purchase_Price * PROMOTION2_PERCENTAGE;
            lblPromotion2Savings.setText(String.format("$ "+"%.2f",Promotion2_Savings)+"  -");
        }
        else
        {
            Promotion2_Savings = 0;
            lblPromotion2Savings.setText(String.format("$ "+"%.2f",Promotion2_Savings)); 
        }
        
        //Calculate Subtotal, Tax and Final Price and Display all values limiting to 2 decimals
        Subtotal_Price = Purchase_Price - Promotion2_Savings;
        lblSubtotalPrice.setText(String.format("$ "+"%.2f",Subtotal_Price));
        
        Tax_Price = Subtotal_Price * TAX_RATE;
        lblTaxPrice.setText(String.format("$ "+"%.2f",Tax_Price));
            
        Final_Price = Subtotal_Price + Tax_Price;
        lblFinalPrice.setText(String.format("$ "+"%.2f",Final_Price));
        
        //Display overall savings for the customer that includes both promotion1 savings and promotion2 savings
        Final_Savings = Promotion1_Savings + Promotion2_Savings;
        lblFinalSavings.setText(String.format("Thank you for Shopping with us. You have saved  $ "+"%.2f",Final_Savings) + "  today");
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        
        // Re-Initializing all the Sizes and quantities for all drinks to "0", upon triggering Reset button
        txtSizeDrink1.setText("0");
        txtQuantityDrink1.setText("0");
        txtSizeDrink2.setText("0");
        txtQuantityDrink2.setText("0");
        txtSizeDrink3.setText("0");
        txtQuantityDrink3.setText("0");
        txtSizeDrink4.setText("0");
        txtQuantityDrink4.setText("0");
        txtSizeDrink5.setText("0");
        txtQuantityDrink5.setText("0");
        txtSizeDrink6.setText("0");
        txtQuantityDrink6.setText("0");

        // Clearing values (moving blanks) on TotalPrices for all drinks, Promotional variables, Subtotal, Tax, Final Price and Final Savings
        lblTotalPriceDrink1.setText("");
        lblTotalPriceDrink2.setText("");
        lblTotalPriceDrink3.setText("");
        lblTotalPriceDrink4.setText("");
        lblTotalPriceDrink5.setText("");
        lblTotalPriceDrink6.setText("");
        lblPromotion1Savings.setText("");
        lblPurchasePrice.setText("");
        lblPromotion2Savings.setText("");
        lblSubtotalPrice.setText("");
        lblTaxPrice.setText("");
        lblFinalPrice.setText("");
        lblFinalSavings.setText("");
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtQuantityDrink1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityDrink1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityDrink1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDecisionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDecisionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDecisionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDecisionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDecisionsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnClear;
    private javax.swing.JLabel lblAssignmentTitle;
    private javax.swing.JLabel lblDummyLine1;
    private javax.swing.JLabel lblDummyLine2;
    private javax.swing.JLabel lblDummyLine3;
    private javax.swing.JLabel lblDummyLine4;
    private javax.swing.JLabel lblFinalPrice;
    private javax.swing.JLabel lblFinalPriceDescription;
    private javax.swing.JLabel lblFinalSavings;
    private javax.swing.JLabel lblIntroduction;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNameDrink1;
    private javax.swing.JLabel lblNameDrink2;
    private javax.swing.JLabel lblNameDrink3;
    private javax.swing.JLabel lblNameDrink4;
    private javax.swing.JLabel lblNameDrink5;
    private javax.swing.JLabel lblNameDrink6;
    private javax.swing.JLabel lblPriceValues;
    private javax.swing.JLabel lblPromotion1Description;
    private javax.swing.JLabel lblPromotion1Details;
    private javax.swing.JLabel lblPromotion1Savings;
    private javax.swing.JLabel lblPromotion2Description;
    private javax.swing.JLabel lblPromotion2Details;
    private javax.swing.JLabel lblPromotion2Savings;
    private javax.swing.JLabel lblPurchasePrice;
    private javax.swing.JLabel lblPurchasePriceDescription;
    private javax.swing.JLabel lblQuantityOptions;
    private javax.swing.JLabel lblSLrep;
    private javax.swing.JLabel lblSizeOptions;
    private javax.swing.JLabel lblSizePriceDrink1;
    private javax.swing.JLabel lblSizePriceDrink2;
    private javax.swing.JLabel lblSizePriceDrink3;
    private javax.swing.JLabel lblSizePriceDrink4;
    private javax.swing.JLabel lblSizePriceDrink5;
    private javax.swing.JLabel lblSizePriceDrink6;
    private javax.swing.JLabel lblSubtotalDescription;
    private javax.swing.JLabel lblSubtotalPrice;
    private javax.swing.JLabel lblTaxDescription;
    private javax.swing.JLabel lblTaxPrice;
    private javax.swing.JLabel lblTotalPriceDrink1;
    private javax.swing.JLabel lblTotalPriceDrink2;
    private javax.swing.JLabel lblTotalPriceDrink3;
    private javax.swing.JLabel lblTotalPriceDrink4;
    private javax.swing.JLabel lblTotalPriceDrink5;
    private javax.swing.JLabel lblTotalPriceDrink6;
    private javax.swing.JTextField txtQuantityDrink1;
    private javax.swing.JTextField txtQuantityDrink2;
    private javax.swing.JTextField txtQuantityDrink3;
    private javax.swing.JTextField txtQuantityDrink4;
    private javax.swing.JTextField txtQuantityDrink5;
    private javax.swing.JTextField txtQuantityDrink6;
    private javax.swing.JTextField txtSizeDrink1;
    private javax.swing.JTextField txtSizeDrink2;
    private javax.swing.JTextField txtSizeDrink3;
    private javax.swing.JTextField txtSizeDrink4;
    private javax.swing.JTextField txtSizeDrink5;
    private javax.swing.JTextField txtSizeDrink6;
    // End of variables declaration//GEN-END:variables
}
